### Register a user
POST http://localhost:3000/mongo/auth/register
Content-Type: application/json

{
    "fullName": "Tanut",
    "email": "Nut@example",
    "password": "123456"
}

### Login with the registered user
POST http://localhost:3000/mongo/auth/login
Content-Type: application/json

{
    "email": "Nut@example",
    "password": "123456"
}